export const MARKETPLACE = {
  FORK_FEE_SOL: 0.5,
  SUBSCRIPTION_FEE_SOL: 0.1,
  PLATFORM_FEE_BPS: 500,          // 5% in basis points
  SUBSCRIPTION_PLATFORM_FEE_BPS: 250,  // 2.5%
  CREATOR_FUND_DAYS: 90,
  ZERO_FEE_DAYS: 30,
  FREE_TIER_AGENTS: 3,
  FREE_TIER_ACTIONS: 100_000,
  PRO_TIER_PRICE_USD: 29,
  PRO_TIER_AGENTS: 10,
  PRO_TIER_ACTIONS: 1_000_000,
  BUILDER_TIER_PRICE_USD: 99,
  BUILDER_TIER_AGENTS: -1,        // unlimited
  BUILDER_TIER_ACTIONS: 10_000_000,
} as const;
