export const PROGRAMS = {
  TAPEDRIVE_PROGRAM_ID: 'YOUR_TAPEDRIVE_PROGRAM_ID',
  MARKETPLACE_PROGRAM_ID: 'YOUR_MARKETPLACE_PROGRAM_ID',
  PAYMENT_402_PROGRAM_ID: 'YOUR_PAYMENT_PROGRAM_ID',
} as const;
